### ISSUE TITLE
suggestion for overview tab

### ISSUE THREAD

**Issue by loksinss** [will0w7/MoneyLooter#12]
hi, i'm not sure if issues is the place for suggestions since i almost never use github, but i wanted to suggest a feature i'd like to see

![image](https://github.com/user-attachments/assets/a4f6263c-4f15-4d75-bb25-4ffc9bc70b4f)
a button on the right window to change between recent items to summary, so you can see how much of each thing you've gathered and how much gold those are worth. so if i do a herb run i can see how how i've gotten total per specific herb vs the others.
thanks!

**Comment by will0w7** [comment]
Yes, this is definitely the place to make suggestions!

I think that's a great idea for a feature. It would be really useful to be able to see a summary of what you've looted and its value. I'll definitely look into how I can implement that.

Thanks for the suggestion!
