### ISSUE TITLE
addon entirely unfunctional

### ISSUE THREAD

**Issue by loksinss** [will0w7/MoneyLooter#4]
i downloaded the addon and the window is moveable but i can't press start or the X button, and if i do the /ml command in chat it refuses to let me press enter to type the message, so nothing happens.

**Comment by will0w7** [comment]
Hello! In which version of the game did this happen to you? From which website did you download it? It would help me if you could share the error message you're getting. Remember that we only support official versions of the game :)

**Comment by loksinss** [comment]
hey, i'm just on the main realm of retail, version 11.0.2
![image](https://github.com/user-attachments/assets/c8ae954f-787e-40f2-be33-1719b9f4218d)
![image](https://github.com/user-attachments/assets/00bbe405-a2ac-4e6e-a836-5b233c0e6ac3)
there are no error messages but the window is open but i can't interact with it other than move it.
and i can't type this message, as if enter doesn't work.

**Comment by will0w7** [comment]
Hey! I just released a patch to fix the issue. It's already available for download from the repository (https://github.com/will0w7/MoneyLooter/releases/tag/0.93.4), Wago (https://addons.wago.io/addons/moneylooter), and in a few minutes it will be available on CurseForge and WoWInterface, as these last two take a while to verify updates.
I'm very sorry for the inconvenience and thank you very much for your report 😊

**Comment by loksinss** [comment]
it seems to work now! thanks ^^

**Comment by will0w7** [comment]
Great! I'm going to close the issue in a couple of hours and if you have any other problems, don't hesitate to let me know!
P.S.: In a day or two I'll release an update with a new, much more modern interface 😊
