### ISSUE TITLE
unable to bring the window back

### ISSUE THREAD

**Issue by loksinss** [will0w7/MoneyLooter#6]
when i close the window, i'm unable to bring it back via /ml show 
the addon works fine, when i logged to an alt the window came up, but as soon as i closed it i'm unable to to get it back.
/ml info works, just for clarification that it's not an input issue

**Comment by will0w7** [comment]
Hey! Thanks for the report. During the development of the new interface, I made several changes to the system and missed checking that part. It's already fixed for version 1.0.10.

**Comment by loksinss** [comment]
works now with the new update! really enjoying the addon btw, feels like there's no others that do this well. thanks 👍

**Comment by will0w7** [comment]
I really appreciate your comment and the bug reports. If you have any suggestions, I'd be happy to hear them 😊
